#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ganado")]
	public partial class DataRemesaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertCamiones(Camiones instance);
    partial void UpdateCamiones(Camiones instance);
    partial void DeleteCamiones(Camiones instance);
    partial void InsertDetalleRemesa(DetalleRemesa instance);
    partial void UpdateDetalleRemesa(DetalleRemesa instance);
    partial void DeleteDetalleRemesa(DetalleRemesa instance);
    partial void InsertGanado(Ganado instance);
    partial void UpdateGanado(Ganado instance);
    partial void DeleteGanado(Ganado instance);
    partial void InsertRemesas(Remesas instance);
    partial void UpdateRemesas(Remesas instance);
    partial void DeleteRemesas(Remesas instance);
    #endregion
		
		public DataRemesaDataContext() : 
				base(global::datos.Properties.Settings.Default.ganadoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataRemesaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataRemesaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataRemesaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataRemesaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Camiones> Camiones
		{
			get
			{
				return this.GetTable<Camiones>();
			}
		}
		
		public System.Data.Linq.Table<DetalleRemesa> DetalleRemesa
		{
			get
			{
				return this.GetTable<DetalleRemesa>();
			}
		}
		
		public System.Data.Linq.Table<Ganado> Ganado
		{
			get
			{
				return this.GetTable<Ganado>();
			}
		}
		
		public System.Data.Linq.Table<Remesas> Remesas
		{
			get
			{
				return this.GetTable<Remesas>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ListarTodosLosCamiones")]
		public ISingleResult<ListarTodosLosCamionesResult> ListarTodosLosCamiones()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ListarTodosLosCamionesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AgregarCamion")]
		public int AgregarCamion([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TamañoCarga", DbType="Decimal(10,2)")] System.Nullable<decimal> tamañoCarga, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Chofer", DbType="VarChar(255)")] string chofer, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EstadoCamion", DbType="VarChar(20)")] string estadoCamion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tamañoCarga, chofer, estadoCamion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ListarCamionesDisponibles")]
		public ISingleResult<ListarCamionesDisponiblesResult> ListarCamionesDisponibles()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ListarCamionesDisponiblesResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Camiones")]
	public partial class Camiones : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdCamion;
		
		private System.Nullable<decimal> _TamañoCarga;
		
		private string _Chofer;
		
		private string _EstadoCamion;
		
		private EntitySet<Remesas> _Remesas;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdCamionChanging(int value);
    partial void OnIdCamionChanged();
    partial void OnTamañoCargaChanging(System.Nullable<decimal> value);
    partial void OnTamañoCargaChanged();
    partial void OnChoferChanging(string value);
    partial void OnChoferChanged();
    partial void OnEstadoCamionChanging(string value);
    partial void OnEstadoCamionChanged();
    #endregion
		
		public Camiones()
		{
			this._Remesas = new EntitySet<Remesas>(new Action<Remesas>(this.attach_Remesas), new Action<Remesas>(this.detach_Remesas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCamion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdCamion
		{
			get
			{
				return this._IdCamion;
			}
			set
			{
				if ((this._IdCamion != value))
				{
					this.OnIdCamionChanging(value);
					this.SendPropertyChanging();
					this._IdCamion = value;
					this.SendPropertyChanged("IdCamion");
					this.OnIdCamionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TamañoCarga", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> TamañoCarga
		{
			get
			{
				return this._TamañoCarga;
			}
			set
			{
				if ((this._TamañoCarga != value))
				{
					this.OnTamañoCargaChanging(value);
					this.SendPropertyChanging();
					this._TamañoCarga = value;
					this.SendPropertyChanged("TamañoCarga");
					this.OnTamañoCargaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chofer", DbType="VarChar(255)")]
		public string Chofer
		{
			get
			{
				return this._Chofer;
			}
			set
			{
				if ((this._Chofer != value))
				{
					this.OnChoferChanging(value);
					this.SendPropertyChanging();
					this._Chofer = value;
					this.SendPropertyChanged("Chofer");
					this.OnChoferChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoCamion", DbType="VarChar(20)")]
		public string EstadoCamion
		{
			get
			{
				return this._EstadoCamion;
			}
			set
			{
				if ((this._EstadoCamion != value))
				{
					this.OnEstadoCamionChanging(value);
					this.SendPropertyChanging();
					this._EstadoCamion = value;
					this.SendPropertyChanged("EstadoCamion");
					this.OnEstadoCamionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Camiones_Remesas", Storage="_Remesas", ThisKey="IdCamion", OtherKey="IdCamion")]
		public EntitySet<Remesas> Remesas
		{
			get
			{
				return this._Remesas;
			}
			set
			{
				this._Remesas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Remesas(Remesas entity)
		{
			this.SendPropertyChanging();
			entity.Camiones = this;
		}
		
		private void detach_Remesas(Remesas entity)
		{
			this.SendPropertyChanging();
			entity.Camiones = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DetalleRemesa")]
	public partial class DetalleRemesa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdDetalleRemesa;
		
		private System.Nullable<int> _IdRemesa;
		
		private System.Nullable<int> _IdGanado;
		
		private EntityRef<Ganado> _Ganado;
		
		private EntityRef<Remesas> _Remesas;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdDetalleRemesaChanging(int value);
    partial void OnIdDetalleRemesaChanged();
    partial void OnIdRemesaChanging(System.Nullable<int> value);
    partial void OnIdRemesaChanged();
    partial void OnIdGanadoChanging(System.Nullable<int> value);
    partial void OnIdGanadoChanged();
    #endregion
		
		public DetalleRemesa()
		{
			this._Ganado = default(EntityRef<Ganado>);
			this._Remesas = default(EntityRef<Remesas>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDetalleRemesa", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdDetalleRemesa
		{
			get
			{
				return this._IdDetalleRemesa;
			}
			set
			{
				if ((this._IdDetalleRemesa != value))
				{
					this.OnIdDetalleRemesaChanging(value);
					this.SendPropertyChanging();
					this._IdDetalleRemesa = value;
					this.SendPropertyChanged("IdDetalleRemesa");
					this.OnIdDetalleRemesaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRemesa", DbType="Int")]
		public System.Nullable<int> IdRemesa
		{
			get
			{
				return this._IdRemesa;
			}
			set
			{
				if ((this._IdRemesa != value))
				{
					if (this._Remesas.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdRemesaChanging(value);
					this.SendPropertyChanging();
					this._IdRemesa = value;
					this.SendPropertyChanged("IdRemesa");
					this.OnIdRemesaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdGanado", DbType="Int")]
		public System.Nullable<int> IdGanado
		{
			get
			{
				return this._IdGanado;
			}
			set
			{
				if ((this._IdGanado != value))
				{
					if (this._Ganado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdGanadoChanging(value);
					this.SendPropertyChanging();
					this._IdGanado = value;
					this.SendPropertyChanged("IdGanado");
					this.OnIdGanadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ganado_DetalleRemesa", Storage="_Ganado", ThisKey="IdGanado", OtherKey="IdGanado", IsForeignKey=true)]
		public Ganado Ganado
		{
			get
			{
				return this._Ganado.Entity;
			}
			set
			{
				Ganado previousValue = this._Ganado.Entity;
				if (((previousValue != value) 
							|| (this._Ganado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ganado.Entity = null;
						previousValue.DetalleRemesa.Remove(this);
					}
					this._Ganado.Entity = value;
					if ((value != null))
					{
						value.DetalleRemesa.Add(this);
						this._IdGanado = value.IdGanado;
					}
					else
					{
						this._IdGanado = default(Nullable<int>);
					}
					this.SendPropertyChanged("Ganado");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Remesas_DetalleRemesa", Storage="_Remesas", ThisKey="IdRemesa", OtherKey="IdRemesa", IsForeignKey=true)]
		public Remesas Remesas
		{
			get
			{
				return this._Remesas.Entity;
			}
			set
			{
				Remesas previousValue = this._Remesas.Entity;
				if (((previousValue != value) 
							|| (this._Remesas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Remesas.Entity = null;
						previousValue.DetalleRemesa.Remove(this);
					}
					this._Remesas.Entity = value;
					if ((value != null))
					{
						value.DetalleRemesa.Add(this);
						this._IdRemesa = value.IdRemesa;
					}
					else
					{
						this._IdRemesa = default(Nullable<int>);
					}
					this.SendPropertyChanged("Remesas");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ganado")]
	public partial class Ganado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdGanado;
		
		private string _Nombre;
		
		private string _Raza;
		
		private string _Tipo;
		
		private System.Nullable<decimal> _Peso;
		
		private string _Descripcion;
		
		private System.Nullable<decimal> _Costo;
		
		private System.Nullable<decimal> _ProduccionLecheDiaria;
		
		private string _EstadoGanado;
		
		private EntitySet<DetalleRemesa> _DetalleRemesa;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdGanadoChanging(int value);
    partial void OnIdGanadoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnRazaChanging(string value);
    partial void OnRazaChanged();
    partial void OnTipoChanging(string value);
    partial void OnTipoChanged();
    partial void OnPesoChanging(System.Nullable<decimal> value);
    partial void OnPesoChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnCostoChanging(System.Nullable<decimal> value);
    partial void OnCostoChanged();
    partial void OnProduccionLecheDiariaChanging(System.Nullable<decimal> value);
    partial void OnProduccionLecheDiariaChanged();
    partial void OnEstadoGanadoChanging(string value);
    partial void OnEstadoGanadoChanged();
    #endregion
		
		public Ganado()
		{
			this._DetalleRemesa = new EntitySet<DetalleRemesa>(new Action<DetalleRemesa>(this.attach_DetalleRemesa), new Action<DetalleRemesa>(this.detach_DetalleRemesa));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdGanado", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdGanado
		{
			get
			{
				return this._IdGanado;
			}
			set
			{
				if ((this._IdGanado != value))
				{
					this.OnIdGanadoChanging(value);
					this.SendPropertyChanging();
					this._IdGanado = value;
					this.SendPropertyChanged("IdGanado");
					this.OnIdGanadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(255)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Raza", DbType="VarChar(255)")]
		public string Raza
		{
			get
			{
				return this._Raza;
			}
			set
			{
				if ((this._Raza != value))
				{
					this.OnRazaChanging(value);
					this.SendPropertyChanging();
					this._Raza = value;
					this.SendPropertyChanged("Raza");
					this.OnRazaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="VarChar(20)")]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this.OnTipoChanging(value);
					this.SendPropertyChanging();
					this._Tipo = value;
					this.SendPropertyChanged("Tipo");
					this.OnTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Peso", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Peso
		{
			get
			{
				return this._Peso;
			}
			set
			{
				if ((this._Peso != value))
				{
					this.OnPesoChanging(value);
					this.SendPropertyChanging();
					this._Peso = value;
					this.SendPropertyChanged("Peso");
					this.OnPesoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(MAX)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Costo", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Costo
		{
			get
			{
				return this._Costo;
			}
			set
			{
				if ((this._Costo != value))
				{
					this.OnCostoChanging(value);
					this.SendPropertyChanging();
					this._Costo = value;
					this.SendPropertyChanged("Costo");
					this.OnCostoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProduccionLecheDiaria", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> ProduccionLecheDiaria
		{
			get
			{
				return this._ProduccionLecheDiaria;
			}
			set
			{
				if ((this._ProduccionLecheDiaria != value))
				{
					this.OnProduccionLecheDiariaChanging(value);
					this.SendPropertyChanging();
					this._ProduccionLecheDiaria = value;
					this.SendPropertyChanged("ProduccionLecheDiaria");
					this.OnProduccionLecheDiariaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoGanado", DbType="VarChar(20)")]
		public string EstadoGanado
		{
			get
			{
				return this._EstadoGanado;
			}
			set
			{
				if ((this._EstadoGanado != value))
				{
					this.OnEstadoGanadoChanging(value);
					this.SendPropertyChanging();
					this._EstadoGanado = value;
					this.SendPropertyChanged("EstadoGanado");
					this.OnEstadoGanadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ganado_DetalleRemesa", Storage="_DetalleRemesa", ThisKey="IdGanado", OtherKey="IdGanado")]
		public EntitySet<DetalleRemesa> DetalleRemesa
		{
			get
			{
				return this._DetalleRemesa;
			}
			set
			{
				this._DetalleRemesa.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DetalleRemesa(DetalleRemesa entity)
		{
			this.SendPropertyChanging();
			entity.Ganado = this;
		}
		
		private void detach_DetalleRemesa(DetalleRemesa entity)
		{
			this.SendPropertyChanging();
			entity.Ganado = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Remesas")]
	public partial class Remesas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdRemesa;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private System.Nullable<int> _IdCamion;
		
		private string _EstadoRemesa;
		
		private System.Nullable<decimal> _TotalCobrar;
		
		private EntitySet<DetalleRemesa> _DetalleRemesa;
		
		private EntityRef<Camiones> _Camiones;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdRemesaChanging(int value);
    partial void OnIdRemesaChanged();
    partial void OnFechaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaChanged();
    partial void OnIdCamionChanging(System.Nullable<int> value);
    partial void OnIdCamionChanged();
    partial void OnEstadoRemesaChanging(string value);
    partial void OnEstadoRemesaChanged();
    partial void OnTotalCobrarChanging(System.Nullable<decimal> value);
    partial void OnTotalCobrarChanged();
    #endregion
		
		public Remesas()
		{
			this._DetalleRemesa = new EntitySet<DetalleRemesa>(new Action<DetalleRemesa>(this.attach_DetalleRemesa), new Action<DetalleRemesa>(this.detach_DetalleRemesa));
			this._Camiones = default(EntityRef<Camiones>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRemesa", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdRemesa
		{
			get
			{
				return this._IdRemesa;
			}
			set
			{
				if ((this._IdRemesa != value))
				{
					this.OnIdRemesaChanging(value);
					this.SendPropertyChanging();
					this._IdRemesa = value;
					this.SendPropertyChanged("IdRemesa");
					this.OnIdRemesaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCamion", DbType="Int")]
		public System.Nullable<int> IdCamion
		{
			get
			{
				return this._IdCamion;
			}
			set
			{
				if ((this._IdCamion != value))
				{
					if (this._Camiones.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdCamionChanging(value);
					this.SendPropertyChanging();
					this._IdCamion = value;
					this.SendPropertyChanged("IdCamion");
					this.OnIdCamionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoRemesa", DbType="VarChar(20)")]
		public string EstadoRemesa
		{
			get
			{
				return this._EstadoRemesa;
			}
			set
			{
				if ((this._EstadoRemesa != value))
				{
					this.OnEstadoRemesaChanging(value);
					this.SendPropertyChanging();
					this._EstadoRemesa = value;
					this.SendPropertyChanged("EstadoRemesa");
					this.OnEstadoRemesaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalCobrar", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> TotalCobrar
		{
			get
			{
				return this._TotalCobrar;
			}
			set
			{
				if ((this._TotalCobrar != value))
				{
					this.OnTotalCobrarChanging(value);
					this.SendPropertyChanging();
					this._TotalCobrar = value;
					this.SendPropertyChanged("TotalCobrar");
					this.OnTotalCobrarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Remesas_DetalleRemesa", Storage="_DetalleRemesa", ThisKey="IdRemesa", OtherKey="IdRemesa")]
		public EntitySet<DetalleRemesa> DetalleRemesa
		{
			get
			{
				return this._DetalleRemesa;
			}
			set
			{
				this._DetalleRemesa.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Camiones_Remesas", Storage="_Camiones", ThisKey="IdCamion", OtherKey="IdCamion", IsForeignKey=true)]
		public Camiones Camiones
		{
			get
			{
				return this._Camiones.Entity;
			}
			set
			{
				Camiones previousValue = this._Camiones.Entity;
				if (((previousValue != value) 
							|| (this._Camiones.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Camiones.Entity = null;
						previousValue.Remesas.Remove(this);
					}
					this._Camiones.Entity = value;
					if ((value != null))
					{
						value.Remesas.Add(this);
						this._IdCamion = value.IdCamion;
					}
					else
					{
						this._IdCamion = default(Nullable<int>);
					}
					this.SendPropertyChanged("Camiones");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DetalleRemesa(DetalleRemesa entity)
		{
			this.SendPropertyChanging();
			entity.Remesas = this;
		}
		
		private void detach_DetalleRemesa(DetalleRemesa entity)
		{
			this.SendPropertyChanging();
			entity.Remesas = null;
		}
	}
	
	public partial class ListarTodosLosCamionesResult
	{
		
		private int _IdCamion;
		
		private System.Nullable<decimal> _TamañoCarga;
		
		private string _Chofer;
		
		private string _EstadoCamion;
		
		public ListarTodosLosCamionesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCamion", DbType="Int NOT NULL")]
		public int IdCamion
		{
			get
			{
				return this._IdCamion;
			}
			set
			{
				if ((this._IdCamion != value))
				{
					this._IdCamion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TamañoCarga", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> TamañoCarga
		{
			get
			{
				return this._TamañoCarga;
			}
			set
			{
				if ((this._TamañoCarga != value))
				{
					this._TamañoCarga = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chofer", DbType="VarChar(255)")]
		public string Chofer
		{
			get
			{
				return this._Chofer;
			}
			set
			{
				if ((this._Chofer != value))
				{
					this._Chofer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoCamion", DbType="VarChar(20)")]
		public string EstadoCamion
		{
			get
			{
				return this._EstadoCamion;
			}
			set
			{
				if ((this._EstadoCamion != value))
				{
					this._EstadoCamion = value;
				}
			}
		}
	}
	
	public partial class ListarCamionesDisponiblesResult
	{
		
		private int _IdCamion;
		
		private System.Nullable<decimal> _TamañoCarga;
		
		private string _Chofer;
		
		public ListarCamionesDisponiblesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCamion", DbType="Int NOT NULL")]
		public int IdCamion
		{
			get
			{
				return this._IdCamion;
			}
			set
			{
				if ((this._IdCamion != value))
				{
					this._IdCamion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TamañoCarga", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> TamañoCarga
		{
			get
			{
				return this._TamañoCarga;
			}
			set
			{
				if ((this._TamañoCarga != value))
				{
					this._TamañoCarga = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chofer", DbType="VarChar(255)")]
		public string Chofer
		{
			get
			{
				return this._Chofer;
			}
			set
			{
				if ((this._Chofer != value))
				{
					this._Chofer = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
